services:
  jekyll:
    image: jekyll/jekyll:latest
    command: >
      bash -c "
        bundle init &&
        bundle add jekyll github-pages &&
        bundle install &&
        jekyll serve --watch --force_polling --verbose --livereload"
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/jekyll
      - bundle:/usr/local/bundle
    environment:
      - JEKYLL_ENV=development

volumes:
  bundle:
